### PR TITLE
Fixes issue #7

### PR DESCRIPTION
**Pull request by notjames**
NT

### CODE REVIEW

**Comment by notjames** [comment]
Not sure why gitlab-ci died as I did not make any changes to any code that would have likely touched the pipeline code. The build died on installation of etcd it seems. Do I need to try and force a retry?

**Comment by ant31** [comment]
can you rebase master (and squash your commits?),   it should work once rebased

**Comment by ant31** [comment]
That was my fault, I did not push the CI fix on master. 

I'm sorry for the delay,
I've rebased and merged the fix on #90, I'll merge asap as you validate it
 

moved to #90

**Comment by notjames** [comment]
Thank you sir! Joe Julian says hi.

**Pull request closed without merging**
